server:
  port: 8081

spring:
  application:
    name: auth-user-service

  data:
    mongodb:
      uri: mongodb+srv://educonnect:educonnect123@educonnect.sjmtr4c.mongodb.net/?appName=educonnect
      database: educonnect
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

eureka:
  client:
    enabled: true

# Disable Kafka
kafka:
  enabled: true

jwt:
  secret: my-super-secret-jwt-key-for-educonnect-platform-minimum-256-bits-required
  expiration: 86400000
  refresh-expiration: 604800000


app:
  two-factor:
    enabled: true
  password-reset:
    token-expiration: 3600000

logging:
  level:
    root: INFO
    com.tcon.auth_user_service: DEBUG
    org.springframework.security: INFO
    org.apache.kafka: OFF
    com.netflix.discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
