server:
  port: 8081

spring:
  application:
    name: auth-user-service

  data:
    mongodb:
      uri: mongodb+srv://educonnect:educonnect123@educonnect.sjmtr4c.mongodb.net/educonnect?appName=educonnect&connectTimeoutMS=20000&socketTimeoutMS=30000&serverSelectionTimeoutMS=30000
      database: educonnect
      auto-index-creation: true

    redis:
      host: redis-15043.c1.us-central1-2.gce.cloud.redislabs.com
      port: 15043
      password: Redies@123
      timeout: 6000ms
      database: 0
      ssl:
        enabled: true
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2

  kafka:
    enabled: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: my-super-secret-jwt-key-for-educonnect-platform-minimum-256-bits-required
  expiration: 86400000
  refresh-expiration: 604800000

app:
  two-factor:
    enabled: true
  password-reset:
    token-expiration: 3600000
  frontend:
    url: http://localhost:5173

services:
  notification:
    url: http://localhost:8085

logging:
  level:
    root: INFO
    com.tcon.auth_user_service: DEBUG
  file:
    name: logs/auth-user-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] traceId=%X{correlationId} userId=%X{userId} %logger{36} - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] traceId=%X{correlationId} userId=%X{userId} %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
